### ISSUE TITLE
supporting land use classification of subset of target classes

### ISSUE THREAD

**Issue by Bart92** [openEOPlatform/openeo-classification#10]
We now throw an error if the user does not allocate all LUCAS subclasses to a target class. Build in support for classification on a subset of the reference data

**Comment by patrick-griffiths** [comment]
small addition: 
It would also be useful if the user can define the new name of the (merged) target class, in the widget and programmatically, currently it does not seem possible
![image](https://user-images.githubusercontent.com/40148967/173300713-f73994d0-6ea0-4388-9c83-d6e62e8eb437.png)

**Comment by Bart92** [comment]
Hi Patrick, the first two are fixed, that is: 
- adding a label (although in the end, the random forest implementation needs numerical values so I also returned a mapping object where number>label can be looked up by the user)
- being able to just do classification on part of total set of land use classes

With respect to the sampling, I think it is very easy to do that as a user, as we are returning a pandas.DataFrame (y) containing the total amount of data found within that specific area. On that, a user can easily apply whichever sampling strategy he wants. Maybe I can just add in the notebook a block where I just use one example of how to sample a pandas dataframe with a strategy ?

**Comment by patrick-griffiths** [comment]
Hi Bart, thanks, that sounds good..
1) even setting an integer value for the new merged output class is valuable, of course... 
2) being able to run on just a suset of all possible classes is essential for the LUCAS datasets but also future ones such as EuroCrops or WorldCover... 
3) demonstrating some advanced sampling functionality in a notebook or as part of the openeo_classification.py would be valuable. Equal sampling (e.g. each class 300 samples) or stratified sampling (e.g. depending on the total samples per class) would be the most important options here..

**Comment by Bart92** [comment]
Hi Patrick, could you have a look at https://github.com/openEOPlatform/SRR3_notebooks/blob/main/notebooks/Demo%20UC9.ipynb to see if this is what you meant?
